^^ Wikiwyg - A Multi-Mode Wiki Editor

Wikiwyg is a WYSIWYG browser editor framework for wikis. It is designed to be pluggable on top of existing wiki engines, with little or no change to the wiki engine's core software.

Wikiwyg has been successfully integrated with the following wiki engines: Socialtext, Kwiki, MediaWiki, Trac and TWiki.

Wikiwyg is designed to be a modal editor. You can flip back and forth between WYSIWYG and WikiText and Preview modes in a single editing session. Other available/possible modes are Raw-HTML and Multi-User modes. Wikiwyg can even be configured to use just WikiText mode, and still provides many user benefits over a traditional textarea.

Wikiwyg currently support WYSIWYG mode in Firefox and IE 6+. It supports WikiText mode in those browsers, and Safari as well. In unsupported browsers, a Wikiwyg integration should fall back to the wiki engine's regular edit interface.
